export const SET_ADD_BLA_STATE = 'SET_ADD_BLA_STATE';
export const SET_CURRENT_STATE = 'SET_CURRENT_STATE';
export const SET_BLA_ID = 'SET_BLA_ID';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_SIDEBAR_NAVIGATE = 'SET_SIDEBAR_NAVIGATE';

export const EDIT_BLA = 'EDIT_BLA';
export const EDIT_BLA_SUCCESS = 'EDIT_BLA_SUCCESS';
export const GET_BLAS_LIST = 'GET_BLAS_LIST';
export const GET_BLAS_LIST_SUCCESS = 'GET_BLAS_LIST_SUCCESS';
export const GET_BLAS_LIST_FAILURE = 'GET_BLAS_LIST_FAILURE';
export const GET_ALL_BLAS_LIST = 'GET_ALL_BLAS_LIST';
export const GET_ALL_BLAS_LIST_SUCCESS = 'GET_ALL_BLAS_LIST_SUCCESS';
export const GET_ALL_BLAS_LIST_FAILURE = 'GET_ALL_BLAS_LIST_FAILURE';
export const GET_BLA_DETAILS = 'GET_BLA_DETAILS';
export const GET_BLA_DETAILS_SUCCESS = 'GET_BLA_DETAILS_SUCCESS';
export const SET_BLA_LIST = 'SET_BLA_LIST';
export const SET_BLA_LIST_SUCCESS = 'SET_BLA_LIST_SUCCESS';
export const GET_DEVICES_BLA_LIST = 'GET_DEVICES_BLA_LIST';
export const GET_DEVICES_BLA_LIST_SUCCESS = 'GET_DEVICES_BLA_LIST_SUCCESS';
export const GET_DEVICES_BLA_LIST_FAILURE = 'GET_DEVICES_BLA_LIST_FAILURE';
export const REMOVE_DEVICE_BLA = 'REMOVE_DEVICE_BLA';
export const REMOVE_DEVICE_BLA_SUCCESS = 'REMOVE_DEVICE_BLA_SUCCESS';
export const REMOVE_DEVICE_BLA_FAILURE = 'REMOVE_DEVICE_BLA_FAILURE';
export const REMOVE_LAST_CREATED_BLA = 'REMOVE_LAST_CREATED_BLA';
export const REMOVE_SELECTED_DEVICE = 'REMOVE_SELECTED_DEVICE';
// Tags
export const SET_TAG_LIST = 'SET_TAG_LIST';
export const SET_TAG_LIST_SUCCESS = 'SET_TAG_LIST_SUCCESS';
export const GET_TAG_LIST = 'GET_TAG_LIST';
export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS';
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE';
export const GET_ALL_TAG_LIST = 'GET_ALL_TAG_LIST';
export const GET_ALL_TAG_LIST_SUCCESS = 'GET_ALL_TAG_LIST_SUCCESS';
export const GET_ALL_TAG_LIST_FAILURE = 'GET_ALL_TAG_LIST_FAILURE';
export const GET_TAG_PROPERTIES = 'GET_TAG_PROPERTIES';
export const GET_TAG_PROPERTIES_SUCCESS = 'GET_TAG_PROPERTIES_SUCCESS';
export const GET_TAG_LIST_BY_DEVICE_ID = 'GET_TAG_LIST_BY_DEVICE_ID';
export const GET_TAG_LIST_BY_DEVICE_ID_SUCCESS =
    'GET_TAG_LIST_BY_DEVICE_ID_SUCCESS';

export const SHOW_LOADER_SUCCESS = 'SHOW_LOADER_SUCCESS';

export const ACTIVATE_DEACTIVATE_BLAS = 'ACTIVATE_DEACTIVATE_BLAS';
export const ACTIVATE_DEACTIVATE_BLAS_SUCCESS =
    'ACTIVATE_DEACTIVATE_BLAS_SUCCESS';

export const EDIT_TAGS = 'EDIT_TAGS';
export const EDIT_TAGS_SUCCESS = 'EDIT_TAGS_SUCCESS';
export const REMOVE_CREATED_TAG_STATUS_REDUX =
    'REMOVE_CREATED_TAG_STATUS_REDUX';

// Device
export const SET_DEVICE_RESPONSE_STATE = 'SET_DEVICE_RESPONSE_STATE';

export const GET_DEVICE_LIST = 'GET_DEVICE_LIST';
export const GET_DEVICE_LIST_SUCCESS = 'GET_DEVICE_LIST_SUCCESS';
export const GET_DEVICE_LIST_FAILURE = 'GET_DEVICE_LIST_FAILURE';

export const GET_ALL_DEVICES_LIST = 'GET_ALL_DEVICES_LIST';
export const GET_ALL_DEVICES_LIST_SUCCESS = 'GET_ALL_DEVICES_LIST_SUCCESS';
export const GET_ALL_DEVICES_LIST_FAILURE = 'GET_ALL_DEVICES_LIST_FAILURE';

export const GET_DEVICE_DETAILS = 'GET_DEVICE_DETAILS';
export const GET_DEVICE_DETAILS_SUCCESS = 'GET_DEVICE_DETAILS_SUCCESS';
export const GET_DEVICE_DETAILS_FAILURE = 'GET_DEVICE_DETAILS_FAILURE';

export const EDIT_DEVICE = 'EDIT_DEVICE';
export const EDIT_DEVICE_SUCCESS = 'EDIT_DEVICE_SUCCESS';
export const ACTIVATE_DEACTIVATE_DEVICES = 'ACTIVATE_DEACTIVATE_DEVICES';
export const ACTIVATE_DEACTIVATE_DEVICES_SUCCESS =
    'ACTIVATE_DEACTIVATE_DEVICES_SUCCESS';
export const CLONE_DEVICES = 'CLONE_DEVICES';
export const CLONE_DEVICES_SUCCESS = 'CLONE_DEVICES_SUCCESS';

export const ACTIVATE_DEACTIVATE_TAGS = 'ACTIVATE_DEACTIVATE_TAGS';
export const ACTIVATE_DEACTIVATE_TAGS_SUCCESS =
    'ACTIVATE_DEACTIVATE_TAGS_SUCCESS';
export const SET_DEVICE_START = 'SET_DEVICE_START';
export const SET_DEVICE_START_SUCCESS = 'SET_DEVICE_START_SUCCESS';
export const SET_DEVICE_START_FAILURE = 'SET_DEVICE_START_FAILURE';

export const SET_DEVICE_STOP = 'SET_DEVICE_STOP';
export const SET_DEVICE_STOP_SUCCESS = 'SET_DEVICE_STOP_SUCCESS';
export const SET_DEVICE_STOP_FAILURE = 'SET_DEVICE_STOP_SUCCESS';

// Tags
export const GET_DATA_TYPES = 'GET_DATA_TYPES';
export const GET_DATA_TYPES_SUCCESS = 'GET_DATA_TYPES_SUCCESS';
export const GET_DATA_TYPES_FAILURE = 'GET_DATA_TYPES_FAILURE';
export const GET_AGGREGATE_METHODS = 'GET_AGGREGATE_METHODS';
export const GET_AGGREGATE_METHODS_SUCCESS = 'GET_AGGREGATE_METHODS_SUCCESS';
export const GET_AGGREGATE_METHODS_FAILURE = 'GET_AGGREGATE_METHODS_FAILURE';

export const GET_TAG_DETAILS = 'GET_TAG_DETAILS';
export const GET_TAG_DETAILS_SUCCESS = 'GET_TAG_DETAILS_SUCCESS';
export const GET_TAG_DETAILS_FAILURE = 'GET_TAG_DETAILS_FAILURE';
export const SET_TAG_RESPONSE_STATE = 'SET_TAG_RESPONSE_STATE';

export const SET_ADD_TAG_DATA = 'SET_ADD_TAG_DATA';

// Upload loader

export const UPLOAD_LOADER_STATE_HANDLER = 'UPLOAD_LOADER_STATE_HANDLER';
