export const SHOW_LOADER_SUCCESS = 'SHOW_LOADER_SUCCESS';

export const GET_KPI_DATA = 'GET_KPI_DATA';
export const GET_KPI_DATA_SUCCESS = 'GET_KPI_DATA_SUCCESS';
export const GET_KPI_DATA_FAILURE = 'GET_KPI_DATA_FAILURE';

export const GET_NODE_LEVEL_LIST = 'GET_NODE_LEVEL_LIST';
export const GET_NODE_LEVEL_LIST_SUCCESS = 'GET_NODE_LEVEL_LIST_SUCCESS';

export const GET_KPI_DETAILS = 'GET_KPI_DETAIL';
export const GET_KPI_DETAILS_SUCCESS = 'GET_KPI_DETAIL_SUCCESS';
export const GET_KPI_DETAILS_FAILURE = 'GET_KPI_DETAIL_FAILURE';

export const SET_KPI_IMPL_STATE = 'SET_KPI_IMPL_STATE';

export const GET_CIRCULATIONCYCLE_LIST = 'GET_CIRCULATIONCYCLE_LIST';
export const GET_CIRCULATIONCYCLE_LIST_SUCCESS =
    'GET_CIRCULATIONCYCLE_LIST_SUCCESS';

export const SET_VALIDATE = 'SET_VALIDATE';
export const SET_VALIDATE_SUCCESS = 'SET_VALIDATE_SUCCESS';
export const SET_VALIDATE_FAILURE = 'SET_VALIDATE_FAILURE';

export const VALIDATE_STATE_UPDATE = 'VALIDATE_STATE_UPDATE';
