export const SHOW_LOADER_SUCCESS = 'SHOW_LOADER_SUCCESS';
export const GET_ALL_DOWNTIMES = 'GET_ALL_DOWNTIMES';
export const GET_ALL_DOWNTIMES_SUCCESS = 'GET_ALL_DOWNTIMES_SUCCESS';
export const GET_ALL_DOWNTIMES_FAIL = 'GET_ALL_DOWNTIMES_FAIL';

export const GET_ALL_REASON_FACTOR = 'GET_ALL_REASON_FACTOR';
export const GET_ALL_REASON_FACTOR_SUCCESS = 'GET_ALL_REASON_FACTOR_SUCCESS';
export const GET_ALL_REASON_FACTOR_FAIL = 'GET_ALL_REASON_FACTOR_FAIL';

export const GET_ALL_REASON_CODE = 'GET_ALL_REASON_CODE';
export const GET_ALL_REASON_CODE_SUCCESS = 'GET_ALL_REASON_CODE_SUCCESS';
export const GET_ALL_REASON_CODE_FAIL = 'GET_ALL_REASON_CODE_FAIL';

export const GET_ALL_REASON_CATEGORY = 'GET_ALL_REASON_CATEGORY';
export const GET_ALL_REASON_CATEGORY_SUCCESS =
    'GET_ALL_REASON_CATEGORY_SUCCESS';
export const GET_ALL_REASON_CATEGORY_FAIL = 'GET_ALL_REASON_CATEGORY_FAIL';

export const SET_REASON_CODE = 'SET_REASON_CODE';
export const SET_REASON_CODE_SUCCESS = 'SET_REASON_CODE_SUCCESS';
export const SET_REASON_CODE_FAIL = 'SET_REASON_CODE_FAIL';

export const DEFAULT_REASON_CODE_VALUE = 'DEFAULT_REASON_CODE_VALUE';
export const DEFAULT_REASON_FACTORY_VALUE = 'DEFAULT_REASON_FACTORY_VALUE';

export const GET_REASON_CODE_NODE_DETAILS = 'GET_REASON_CODE_NODE_DETAILS';
export const GET_REASON_CODE_NODE_DETAILS_SUCCESS =
    'GET_REASON_CODE_NODE_DETAILS_SUCCESS';
export const GET_REASON_CODE_NODE_DETAILS_FAIL =
    'GET_REASON_CODE_NODE_DETAILS_FAIL';
