import { ReactComponent as DataIcon } from 'assets/icons/dataIcon.svg';
import { ReactComponent as ConfigurationIcon } from 'assets/icons/configurationIcon.svg';
import { ReactComponent as DataExplorer } from 'assets/icons/dataExplorer.svg';
import { ReactComponent as UserManagementIcon } from 'assets/icons/userManagement.svg';
import { ReactComponent as DeviceConnectionIcon } from 'assets/icons/deviceConnection.svg';
import { ReactComponent as TransformIcon } from 'assets/icons/transform.svg';
import { ReactComponent as AssetModellerIcon } from 'assets/icons/assetModeller.svg';
import { ReactComponent as ContextualizationIcon } from 'assets/icons/contextualizationIcon.svg';
import { ReactComponent as DataTablesIcon } from 'assets/icons/dataTables.svg';
import { ReactComponent as DeviceListIcon } from 'assets/icons/deviceList.svg';
import { ReactComponent as UserIcon } from 'assets/icons/userIcon.svg';
import { ReactComponent as RoleIcon } from 'assets/icons/rolesIcon.svg';
import { ReactComponent as HomeIcon } from 'assets/icons/home.svg';
import { ReactComponent as DataVisualization } from 'assets/icons/dataVisualization.svg';
import { ReactComponent as DashboardBuilder } from 'assets/icons/dashboardBuilderIcon.svg';
import { ReactComponent as ReportHeader } from 'assets/icons/reportingHeader.svg';
import { ReactComponent as ReportConfigurator } from 'assets/icons/reportConfiguratorIcon.svg';
import { ReactComponent as UseCases } from 'assets/icons/useCases.svg';
import { ReactComponent as BoilerEfficiencyMonitoring } from 'assets/icons/boilerEfficiencyMonitoring.svg';
import { ReactComponent as NocilDashboard } from 'assets/icons/nocilDashboard.svg';
import { ReactComponent as ManualEntry } from 'assets/icons/manualEntry.svg';
import { ReactComponent as OperatorEntry } from 'assets/icons/operatorEntry.svg';
import { ReactComponent as Groups } from 'assets/icons/groups.svg';
import { ReactComponent as Settings } from 'assets/icons/sideNavSettingsIcon.svg';
import { ReactComponent as ConfigIcon } from 'assets/icons/config.svg';
import { ReactComponent as FillingPackagingIcon } from 'assets/icons/fillingPackagingIcon.svg';
import { ReactComponent as BusinessIntIcon } from 'assets/icons/businessIntegrator.svg';
import { ReactComponent as CustomContextIcon } from 'assets/icons/customContext.svg';
import { ReactComponent as KpiIcon } from 'assets/icons/kpiIcon.svg';
import { ReactComponent as AutomationIcon } from 'assets/icons/automationIcon.svg';
import { ReactComponent as FormIcon } from 'assets/icons/formIcon.svg';
import { ReactComponent as ConnectionsIcon } from 'assets/icons/connectionsIcon.svg';
import { ReactComponent as MonitoringIcon } from 'assets/icons/monitoringIcon.svg';
import { ReactComponent as OperationsIcon } from 'assets/icons/operationsIcon.svg';
import { ReactComponent as MappingIcon } from 'assets/icons/mappingIcon.svg';
import { ReactComponent as AttributeIcon } from 'assets/icons/attributeIcon.svg';
import { ReactComponent as TableIcon } from 'assets/icons/tableIcon.svg';
import { ReactComponent as TimeCapsuleIcon } from 'assets/icons/timeCapsuleIcon.svg';
import { ReactComponent as ImplementationIcon } from 'assets/icons/implementationIcon.svg';
import { ReactComponent as ManualFormIcon } from 'assets/icons/manualForm.svg';
import { ReactComponent as ReasonCodeIcon } from 'assets/icons/reasonCodeEntry.svg';
import { Tag } from 'antd';

export const data = [
    {
        name: 'Home',
        breadcrumb: 'Home',
        key: 'Home',
        icon: <HomeIcon />,
        path: '/home',
        exact: true,
    },
    {
        id: 51,
        name: 'Dashboards',
        breadcrumb: 'Dashboards',
        key: 'Dashboards',
        icon: <Settings />,
        // path: '/dashboards',
        exact: true,
    },
    {
        id: 4,
        name: <>{'Brabo AI Assistant   '}<Tag color="blue">Beta</Tag></>,
        breadcrumb: 'Brabo AI Assistant',
        key: 'Brabo AI Assistant',
        icon: <BusinessIntIcon />,
        path: '/brabo-assistant',
        exact: true,
        children: [],
    },
    {
        id: 73,
        name: 'Manual Forms',
        breadcrumb: 'Manual Forms',
        key: 'Manual Forms',
        icon: <ManualFormIcon />,
        path: '/manual-forms',
        exact: true,
        children: [
            {
                id: 74,
                name: 'Line 3 - Reason Code Entry',
                breadcrumb: 'Line 3 - Reason Code Entry',
                key: 'reason-code',
                icon: <ReasonCodeIcon />,
                path: '/manual-forms/reason-code',
                exact: true,
                children: [],
            },
        ],
    },
    {
        id: 71,
        name: 'Connect',
        breadcrumb: 'Connect',
        key: 'Connect',
        icon: <DataIcon />,
        path: '/device-management',
        exact: true,
        children: [
            {
                id: 70,
                name: 'Device Management',
                breadcrumb: 'Device Management',
                key: 'Device Management',
                icon: <DeviceConnectionIcon />,
                path: '/device-connection',
                exact: true,
                children: [
                    {
                        id: 4,
                        name: 'BLAs',
                        breadcrumb: 'BLAs',
                        key: 'BLA',
                        icon: <DeviceListIcon />,
                        path: '/device-management/blas',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 5,
                        name: 'Devices',
                        breadcrumb: 'Devices',
                        key: 'Devices',
                        icon: <DeviceListIcon />,
                        path: '/device-management/devices',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 6,
                        name: 'Tags',
                        breadcrumb: 'Tags',
                        key: 'Tags',
                        icon: <DeviceListIcon />,
                        path: '/device-management/tags',
                        exact: true,
                        children: [],
                    },
                ],
            },
            {
                id: 78,
                name: 'Business Integrator',
                breadcrumb: 'Business Integrator',
                key: 'Business Integrator',
                icon: <BusinessIntIcon />,
                path: '/home',
                exact: true,
                children: [
                    {
                        id: 79,
                        name: 'Connections',
                        breadcrumb: 'Connections',
                        key: 'Connections',
                        icon: <ConnectionsIcon />,
                        path: '/home',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 80,
                        name: 'Mapping',
                        breadcrumb: 'Mapping',
                        key: 'Mapping',
                        icon: <MappingIcon />,
                        path: '/home',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 81,
                        name: 'Operations',
                        breadcrumb: 'Operations',
                        key: 'Operations',
                        icon: <OperationsIcon />,
                        path: '/home',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 82,
                        name: 'Monitoring',
                        breadcrumb: 'Monitoring',
                        key: 'Monitoring',
                        icon: <MonitoringIcon />,
                        path: '/home',
                        exact: true,
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        id: 74,
        name: 'Transform',
        breadcrumb: 'Transform',
        key: 'Transform',
        icon: <TransformIcon />,
        path: '/home',
        exact: true,
        children: [
            {
                id: 75,
                name: 'Contextualization',
                breadcrumb: 'Contextualization',
                key: 'Contextualization',
                icon: <ContextualizationIcon />,
                path: '/home',
                exact: true,
                children: [
                    {
                        id: 76,
                        name: 'Asset Modeller',
                        breadcrumb: 'Asset Modeller',
                        key: 'Asset Modeller',
                        icon: <AssetModellerIcon />,
                        exact: true,
                        children: [],
                    },
                    {
                        id: 77,
                        name: 'Custom Context',
                        breadcrumb: 'Custom Context',
                        key: 'Custom Context',
                        icon: <CustomContextIcon />,
                        path: '/home',
                        exact: true,
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        id: 165,
        name: 'Configure',
        breadcrumb: 'Configure',
        key: 'Configure',
        icon: <ConfigIcon />,
        exact: true,
        children: [
            {
                id: 166,
                name: 'Data Dictionary',
                breadcrumb: 'Data Dictionary',
                key: 'Data-Dictionary',
                icon: <DeviceConnectionIcon />,
                path: '/configure/data-dictionary',
                exact: true,
                children: [
                    {
                        id: 167,
                        name: 'Attribute',
                        breadcrumb: 'Attribute',
                        key: 'Attribute Definition',
                        icon: <DeviceListIcon />,
                        path: '/configure/data-dictionary/attribute',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 168,
                        name: 'Time Capsule',
                        breadcrumb: 'Time Capsule',
                        key: 'Time Capsule Definition',
                        icon: <DeviceListIcon />,
                        path: '/configure/data-dictionary/time-capsule',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 169,
                        name: 'Table',
                        breadcrumb: 'Table',
                        key: 'Table Definition',
                        icon: <DeviceListIcon />,
                        path: '/configure/data-dictionary/table',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 170,
                        name: 'KPIs',
                        breadcrumb: 'KPIs',
                        key: 'KPI Definition',
                        icon: <DeviceListIcon />,
                        path: '/configure/data-dictionary/kpi',
                        exact: true,
                        children: [],
                    },
                ],
            },
            {
                id: 14,
                name: 'Implementation',
                breadcrumb: 'Implementation',
                key: 'Implementation',
                icon: <ImplementationIcon />,
                path: '/configure/implementation',
                exact: true,
                children: [
                    {
                        id: 85,
                        name: 'Attribute',
                        breadcrumb: 'Attribute',
                        key: 'Attribute Implementation',
                        icon: <AttributeIcon />,
                        path: '/configure/implementation/attribute',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 86,
                        name: 'Time Capsule',
                        breadcrumb: 'Time Capsule',
                        key: 'Time Capsule Implementation',
                        icon: <TimeCapsuleIcon />,
                        path: '/configure/implementation/time-Capsule',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 87,
                        name: 'Table',
                        breadcrumb: 'Table',
                        key: 'Table Implementation',
                        icon: <TableIcon />,
                        path: '/configure/implementation/table',
                        exact: true,
                        children: [],
                    },
                ],
            },
            {
                id: 73,
                name: 'KPIs',
                breadcrumb: 'KPIs',
                key: 'KPIs',
                icon: <KpiIcon />,
                path: '/home',
                exact: true,
                children: [
                    {
                        id: 88,
                        name: 'KPI Implementation',
                        breadcrumb: 'KPI',
                        key: 'KPI Implementation',
                        icon: <KpiIcon />,
                        path: '/configure/kpis/kpi-implementation',
                        exact: true,
                        children: [],
                    },
                ],
            },
            {
                id: 15,
                name: 'Dashboard Builder',
                breadcrumb: 'Dashboard Builder',
                key: 'Dashboard Builder',
                icon: <DashboardBuilder />,
                path: '/dashboard-builder',
                exact: true,
                disabled: false,
                children: [],
            },
            {
                id: 55,
                name: 'Dashboard Reporting',
                breadcrumb: 'Dashboard Reporting',
                key: 'Dashboard Reporting',
                icon: <ReportHeader />,
                exact: true,
                children: [
                    {
                        id: 72,
                        name: 'Report Configurator',
                        breadcrumb: 'Report Configurator',
                        key: 'Report Configuration',
                        icon: <ReportConfigurator />,
                        path: '/report-configurator',
                        exact: true,
                    },
                    {
                        id: 16,
                        name: 'Reports',
                        breadcrumb: 'Reports',
                        key: 'Reports',
                        icon: <ReportConfigurator />,
                        path: '/reports',
                        exact: true,
                    },
                ],
            },
            {
                id: 73,
                name: 'Forms',
                breadcrumb: 'Forms',
                key: 'Forms',
                icon: <FormIcon />,
                path: '/home',
                exact: true,
                children: [],
            },
        ],
    },
    {
        id: 61,
        name: 'Automate',
        breadcrumb: 'Automate',
        key: 'Automate',
        icon: <AutomationIcon />,
        path: '/home',
        exact: true,
        children: [
            {
                id: 60,
                name: 'Workflows',
                breadcrumb: 'Workflows',
                key: 'Workflows',
                icon: <DeviceListIcon />,
                path: '/home',
                exact: true,
            },
            {
                id: 59,
                name: 'Notifications',
                breadcrumb: 'Notifications',
                key: 'Notifications',
                icon: <DeviceListIcon />,
                path: '/home',
                exact: true,
            },
        ],
    },
    {
        id: 58,
        name: 'Data Explorer',
        breadcrumb: 'Data Explorer',
        key: 'Data Explorer',
        icon: <DataExplorer />,
        exact: true,
        children: [
            {
                id: 11,
                name: 'Data Visualization',
                breadcrumb: 'Data Visualization',
                key: 'Data Visualization',
                icon: <DataVisualization />,
                path: '/data-visualization',
                exact: true,
                children: [
                    {
                        id: 162,
                        name: 'Trending',
                        breadcrumb: 'Trending',
                        key: 'Trending',
                        icon: <ConfigurationIcon />,
                        path: '/data-visualization/trending',
                        exact: true,
                    },
                    {
                        id: 163,
                        name: 'Data Table',
                        breadcrumb: 'Data Table',
                        key: 'Data Table',
                        icon: <DataTablesIcon />,
                        path: '/data-visualization/data-table',
                        exact: true,
                    },
                ],
            },
        ],
    },
    {
        id: 57,
        name: 'Use Cases',
        breadcrumb: 'Use Cases',
        key: 'Use Cases',
        icon: <UseCases />,
        exact: true,
        children: [
            {
                id: 56,
                name: 'CPG OEE Monitoring',
                breadcrumb: 'CPG OEE Monitoring',
                key: 'CPG OEE Monitoring',
                icon: <FillingPackagingIcon />,
                exact: true,
                children: [],
            },
            {
                id: 59,
                name: 'Boiler Efficiency Monitoring',
                breadcrumb: 'Boiler Efficiency Monitoring',
                key: 'Boiler Efficiency Monitoring',
                icon: <BoilerEfficiencyMonitoring />,
                exact: true,
                children: [],
            },
            // menus hidden for now
            // {
            //     id: 55,
            //     name: 'Chemical Process Monitoring',
            //     breadcrumb: 'Chemical Process Monitoring',
            //     key: 'aarti_apple',
            //     icon: <UserIcon />,
            //     exact: true,
            //     children: [],
            // },
            // {
            //     id: 53,
            //     name: 'Critical Asset Monitoring',
            //     breadcrumb: 'Critical Asset Monitoring',
            //     key: 'eberspacher',
            //     icon: <UserIcon />,
            //     path: '/use-cases/robotic-arm',
            //     exact: true,
            //     children: [],
            // },
            {
                id: 52,
                name: 'Boiler Efficiency',
                breadcrumb: 'nocil',
                key: 'Boiler Efficiency',
                icon: <BoilerEfficiencyMonitoring />,
                // path: '/nocil/boiler-efficiency',
                exact: true,
                children: [
                    {
                        id: 9,
                        name: 'NOCIL Dashboard',
                        breadcrumb: 'nocil',
                        key: 'NOCIL Dashboard',
                        icon: <NocilDashboard />,
                        path: '/nocil/nocil-dashboard',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 10,
                        name: 'Manual Entry',
                        breadcrumb: 'nocil',
                        key: 'Manual Entry',
                        icon: <ManualEntry />,
                        path: '/nocil/manual-entry',
                        exact: true,
                        children: [],
                    },
                    {
                        id: 13,
                        name: 'Operator Entry',
                        breadcrumb: 'nocil',
                        key: 'Operator Entry',
                        icon: <OperatorEntry />,
                        path: '/nocil/operator-entry',
                        exact: true,
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        id: 51,
        name: 'User Management',
        breadcrumb: 'User Management',
        key: 'User Management',
        icon: <UserManagementIcon />,
        exact: true,
        children: [
            {
                id: 1,
                name: 'Users',
                breadcrumb: 'Users',
                key: 'Users',
                icon: <UserIcon />,
                path: '/user-management/users',
                exact: true,
                children: [],
            },
            {
                id: 2,
                name: 'Groups',
                breadcrumb: 'Groups',
                key: 'Resource Groups',
                icon: <Groups />,
                path: '/user-management/groups',
                exact: true,
                children: [],
            },
            {
                id: 3,
                name: 'Roles',
                breadcrumb: 'Roles',
                key: 'Roles',
                icon: <RoleIcon />,
                path: '/user-management/roles',
                exact: true,
                children: [],
            },
        ],
    },
    {
        id: 50,
        name: 'Settings',
        breadcrumb: 'Settings',
        key: 'Settings',
        icon: <Settings />,
        path: '/settings',
        exact: true,
        children: [
            {
                id: 12,
                name: 'Calendar Configurator',
                breadcrumb: 'Calendar Configurator',
                key: 'Calendar Configuration',
                path: '/settings/calendar-configurator',
                exact: true,
                children: [],
            },
        ],
    },
];
